---

name: release
on:
  workflow_run:
    workflows: ["unit-tests", "linting"]
    types:
      - completed

jobs:
  release:
    if: ${{ github.ref == 'master' && (github.event.workflow_run.name == 'unit-tests' && github.event.workflow_run.conclusion == 'success') && (github.event.workflow_run.name == 'linting' && github.event.workflow_run.conclusion == 'success') }}
    runs-on: ubuntu-latest
    name: semantic-release
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          always-auth: false
          node-version: ${{ matrix.node-version }}

      - name: Run yarn install
        run: yarn install --ignore-engines --ignore-scripts

      - name: Release
        run: yarn run semantic-release
